/* ── Product Data ─────────────────────────────────────── */

const PRODUCTS = [
    {
        id: 'CX-26-001',
        name: 'Sleeping Cat Plush Toy',
        category: 'toys-games',
        catLabel: 'Toys & Games',
        badge: 'deal',
        price: 249,
        pLabel: 'Now At',
        pDisplay: '₹249',
        pOld: '₹899',
        discount: 72,
        desc: 'A realistic sleeping cat plush toy with soft premium fur and calming breathing sound effects. Perfect as a stress-relief companion, cute desk decor, or a cozy gift for kids and cat lovers.',
        tags: ['Soft Toy', 'Cat Plush', 'Sound Effect', 'Stress Relief', 'Kids Gift', 'Desk Decor'],
        link: 'https://amzn.to/3PqDIub',
        publishDate: '2026-05-22'
    },
    {
        id: 'CX-26-002',
        name: 'Portronics Clamp M5 Car Phone Holder',
        category: 'mobile-accessories',
        catLabel: 'Mobile Accessories',
        badge: 'deal',
        price: 336,
        pLabel: 'Now At',
        pDisplay: '₹336',
        pOld: '₹999',
        discount: 66,
        desc: 'A sturdy shockproof car phone holder with powerful suction grip, 360° rotation, and single-hand operation. Keeps your smartphone secure and accessible even on rough drives.',
        tags: ['Car Mount', '360 Rotation', 'Shockproof', 'Strong Grip', 'Hands-Free', 'Portronics'],
        link: 'https://amzn.to/43lER9t',
        publishDate: '2026-05-22'
    },
    {
        id: 'CX-26-003',
        name: 'Portronics Car Power 16 Fast Car Charger',
        category: 'mobile-accessories',
        catLabel: 'Mobile Accessories',
        badge: 'deal',
        price: 377,
        pLabel: 'Now At',
        pDisplay: '₹377',
        pOld: '₹999',
        discount: 62,
        desc: 'A compact 51W dual-port fast car charger with 33W Type-C PD and 18W USB fast charging. Perfect for charging smartphones, tablets, and other devices quickly during travel or daily commutes.',
        tags: ['Fast Charging', '51W Output', 'Type-C PD', 'Dual Port', 'Car Charger', 'Portronics'],
        link: 'https://amzn.to/4wQ15hF',
        publishDate: '2026-05-22'
    },
    {
        id: 'CX-26-004',
        name: 'WOSCHER AutoVac Pro Car Vacuum Cleaner',
        category: 'car-accessories',
        catLabel: 'Car Accessories',
        badge: 'deal',
        price: 1550,
        pLabel: 'Now At',
        pDisplay: '₹1550',
        pOld: '₹2499',
        discount: 38,
        desc: 'A powerful 140W handheld car vacuum cleaner with 5000PA suction, washable HEPA filter, and multiple nozzle attachments for deep interior cleaning. Ideal for removing dust, pet hair, and debris from hard-to-reach areas.',
        tags: ['Car Vacuum', '5000PA Suction', 'HEPA Filter', 'Portable', 'Deep Cleaning', 'WOSCHER'],
        link: 'https://amzn.to/3Rqq5M2',
        publishDate: '2026-05-22'
    },
    {
        id: 'CX-26-005',
        name: 'APPUCOCO Mini Car Trash Bin',
        category: 'car-accessories',
        catLabel: 'Car Accessories',
        badge: 'deal',
        price: 180,
        pLabel: 'Now At',
        pDisplay: '₹180',
        pOld: '₹699',
        discount: 74,
        desc: 'A compact mini car trash bin designed to keep your car clean and organized. Fits easily in cup holders, car doors, or center consoles and can also be used as a desk organizer at home or office.',
        tags: ['Car Dustbin', 'Compact Design', 'Cup Holder Fit', 'Organizer', 'Travel Essential', 'Portable'],
        link: 'https://amzn.to/4v7iJMe',
        publishDate: '2026-05-22'
    },
    {
        id: 'CX-26-006',
        name: 'DETACHI Car Tissue Holder',
        category: 'car-accessories',
        catLabel: 'Car Accessories',
        badge: 'deal',
        price: 261,
        pLabel: 'Now At',
        pDisplay: '₹261',
        pOld: '₹999',
        discount: 74,
        desc: 'A premium faux leather car tissue holder designed to keep tissues easily accessible while driving. Clips securely onto sun visors, seat backs, or car doors for a cleaner and more organized interior.',
        tags: ['Tissue Holder', 'Car Organizer', 'Faux Leather', 'Space Saving', 'Car Interior', 'DETACHI'],
        link: 'https://amzn.to/3RA6R6H',
        publishDate: '2026-05-22'
    },
    {
        id: 'CX-26-007',
        name: 'Godrej aer O Hanging Car Air Freshener Pack',
        category: 'car-accessories',
        catLabel: 'Car Accessories',
        badge: 'hot',
        price: 245,
        pLabel: 'Now At',
        pDisplay: '₹245',
        pOld: '₹297',
        discount: 18,
        desc: 'A stylish hanging gel-based car air freshener pack with long-lasting fragrance for up to 30 days. Designed to keep your car fresh, odor-free, and pleasant during every drive.',
        tags: ['Air Freshener', 'Long Lasting', 'Car Interior', 'Odor Control', 'Gel Freshener', 'Godrej'],
        link: 'https://amzn.to/49iFcgO',
        publishDate: '2026-05-22'
    },
    {
        id: 'CX-26-008',
        name: 'Yuoyar Magnetic Sunglasses Holder for Car',
        category: 'car-accessories',
        catLabel: 'Car Accessories',
        badge: 'deal',
        price: 289,
        pLabel: 'Now At',
        pDisplay: '₹289',
        pOld: '₹999',
        discount: 71,
        desc: 'A premium magnetic leather sunglasses holder designed for car visors. Keeps your sunglasses secure, scratch-free, and easily accessible while driving with convenient single-hand operation.',
        tags: ['Sunglasses Holder', 'Magnetic Clip', 'Car Organizer', 'Leather Finish', 'Visor Accessory', 'Yuoyar'],
        link: 'https://amzn.to/4fzffNF',
        publishDate: '2026-05-22'
    },
    {
        id: 'CX-26-009',
        name: 'Cinati Under Desk Cable Management Tray',
        category: 'desk-setup',
        catLabel: 'Desk Setup',
        badge: 'hot',
        price: 1999,
        pLabel: 'Now At',
        pDisplay: '₹1999',
        pOld: '₹2999',
        discount: 33,
        desc: 'An extra-large no-drill under desk cable management tray designed to organize wires, adapters, and power strips neatly. Features sturdy metal construction, clamp installation, and a clean clutter-free setup for home or office desks.',
        tags: ['Cable Management', 'Desk Setup', 'No Drill', 'Wire Organizer', 'Workspace', 'Cinati'],
        link: 'https://amzn.to/42Z9wtb',
        publishDate: '2026-05-27'
    },
    {
        id: 'CX-26-010',
        name: 'VSDinside 18-Key Stream Controller Macro Pad',
        category: 'desk-setup',
        catLabel: 'Desk Setup',
        badge: 'hot',
        price: 8194.87,
        pLabel: 'Now At',
        pDisplay: '₹8,194',
        pOld: '₹30,314',
        discount: 73,
        desc: 'A premium 18-key programmable macro pad with customizable LCD keys, RGB lighting, and one-touch shortcuts for gaming, streaming, editing, and productivity workflows. Perfect for creators, streamers, and advanced desk setups.',
        tags: ['Macro Keyboard', 'Stream Deck', 'RGB', 'Gaming Setup', 'Productivity', 'VSDinside'],
        link: 'https://amzn.to/4vivJi9',
        publishDate: '2026-05-27'
    },
    {
        id: 'CX-26-011',
        name: 'Portronics Tornado High-Speed Air Duster',
        category: 'desk-setup',
        catLabel: 'Desk Setup',
        badge: 'hot',
        price: 2399,
        pLabel: 'Now At',
        pDisplay: '₹2,399',
        pOld: '₹4,999',
        discount: 52,
        desc: 'A powerful cordless handheld air duster with up to 130000 RPM airflow, adjustable speed modes, and Type-C charging. Perfect for cleaning keyboards, PCs, cameras, car interiors, and hard-to-reach electronics.',
        tags: ['Air Duster', 'Desk Setup', 'Cleaning Tool', 'Rechargeable', 'High Speed', 'Portronics'],
        link: 'https://amzn.to/4dyVTqJ',
        publishDate: '2026-05-27'
    },
    {
        id: 'CX-26-012',
        name: 'PxIn Privacy Screen Filter for Laptop',
        category: 'desk-setup',
        catLabel: 'Desk Setup',
        badge: 'hot',
        price: 1598,
        pLabel: 'Now At',
        pDisplay: '₹1,598',
        pOld: '₹2,999',
        discount: 47,
        desc: 'A premium anti-glare privacy screen filter with blue light protection designed to reduce eye strain and protect sensitive information in public spaces. Ideal for laptops and work-from-anywhere setups.',
        tags: ['Privacy Screen', 'Anti Glare', 'Blue Light Filter', 'Laptop Accessory', 'Eye Protection', 'PxIn'],
        link: 'https://amzn.to/4nPp9gm',
        publishDate: '2026-05-27'
    },
    {
        id: 'CX-26-013',
        name: 'Portronics Mport 8 USB-C Hub',
        category: 'desk-setup',
        catLabel: 'Desk Setup',
        badge: 'deal',
        price: 1073,
        pLabel: 'Now At',
        pDisplay: '₹1,073',
        pOld: '₹2,999',
        discount: 64,
        desc: 'An 8-in-1 USB-C docking hub with 4K HDMI output, Ethernet, USB 3.0, SD/microSD card readers, and PD charging support. A compact productivity essential for laptops, MacBooks, and modern desk setups.',
        tags: ['USB-C Hub', 'Docking Station', '4K HDMI', 'Desk Setup', 'Productivity', 'Portronics'],
        link: 'https://amzn.to/4dOFopx',
        publishDate: '2026-05-27'
    }
];