/* ── Product Data ─────────────────────────────────────── */

const PRODUCTS = [
    {
        id: 'CX-26-001',
        name: 'Sleeping Cat Plush Toy',
        category: 'toys-games',
        catLabel: 'Toys & Games',
        badge: 'deal',
        price: 249,
        pLabel: 'Now At',
        pDisplay: '₹249',
        pOld: '₹899',
        discount: 72,
        desc: 'A realistic sleeping cat plush toy with soft premium fur and calming breathing sound effects. Perfect as a stress-relief companion, cute desk decor, or a cozy gift for kids and cat lovers.',
        tags: ['Soft Toy', 'Cat Plush', 'Sound Effect', 'Stress Relief', 'Kids Gift', 'Desk Decor'],
        link: 'https://amzn.to/3PqDIub',
        publishDate: '2026-05-22'
    },
    {
        id: 'CX-26-002',
        name: 'Portronics Clamp M5 Car Phone Holder',
        category: 'mobile-accessories',
        catLabel: 'Mobile Accessories',
        badge: 'deal',
        price: 336,
        pLabel: 'Now At',
        pDisplay: '₹336',
        pOld: '₹999',
        discount: 66,
        desc: 'A sturdy shockproof car phone holder with powerful suction grip, 360° rotation, and single-hand operation. Keeps your smartphone secure and accessible even on rough drives.',
        tags: ['Car Mount', '360 Rotation', 'Shockproof', 'Strong Grip', 'Hands-Free', 'Portronics'],
        link: 'https://amzn.to/43lER9t',
        publishDate: '2026-05-22'
    },
    {
        id: 'CX-26-003',
        name: 'Portronics Car Power 16 Fast Car Charger',
        category: 'mobile-accessories',
        catLabel: 'Mobile Accessories',
        badge: 'deal',
        price: 377,
        pLabel: 'Now At',
        pDisplay: '₹377',
        pOld: '₹999',
        discount: 62,
        desc: 'A compact 51W dual-port fast car charger with 33W Type-C PD and 18W USB fast charging. Perfect for charging smartphones, tablets, and other devices quickly during travel or daily commutes.',
        tags: ['Fast Charging', '51W Output', 'Type-C PD', 'Dual Port', 'Car Charger', 'Portronics'],
        link: 'https://amzn.to/4wQ15hF',
        publishDate: '2026-05-22'
    },
    {
        id: 'CX-26-004',
        name: 'WOSCHER AutoVac Pro Car Vacuum Cleaner',
        category: 'car-accessories',
        catLabel: 'Car Accessories',
        badge: 'deal',
        price: 1550,
        pLabel: 'Now At',
        pDisplay: '₹1550',
        pOld: '₹2499',
        discount: 38,
        desc: 'A powerful 140W handheld car vacuum cleaner with 5000PA suction, washable HEPA filter, and multiple nozzle attachments for deep interior cleaning. Ideal for removing dust, pet hair, and debris from hard-to-reach areas.',
        tags: ['Car Vacuum', '5000PA Suction', 'HEPA Filter', 'Portable', 'Deep Cleaning', 'WOSCHER'],
        link: 'https://amzn.to/3Rqq5M2',
        publishDate: '2026-05-22'
    },
    {
        id: 'CX-26-005',
        name: 'APPUCOCO Mini Car Trash Bin',
        category: 'car-accessories',
        catLabel: 'Car Accessories',
        badge: 'deal',
        price: 180,
        pLabel: 'Now At',
        pDisplay: '₹180',
        pOld: '₹699',
        discount: 74,
        desc: 'A compact mini car trash bin designed to keep your car clean and organized. Fits easily in cup holders, car doors, or center consoles and can also be used as a desk organizer at home or office.',
        tags: ['Car Dustbin', 'Compact Design', 'Cup Holder Fit', 'Organizer', 'Travel Essential', 'Portable'],
        link: 'https://amzn.to/4v7iJMe',
        publishDate: '2026-05-22'
    },
    {
        id: 'CX-26-006',
        name: 'DETACHI Car Tissue Holder',
        category: 'car-accessories',
        catLabel: 'Car Accessories',
        badge: 'deal',
        price: 261,
        pLabel: 'Now At',
        pDisplay: '₹261',
        pOld: '₹999',
        discount: 74,
        desc: 'A premium faux leather car tissue holder designed to keep tissues easily accessible while driving. Clips securely onto sun visors, seat backs, or car doors for a cleaner and more organized interior.',
        tags: ['Tissue Holder', 'Car Organizer', 'Faux Leather', 'Space Saving', 'Car Interior', 'DETACHI'],
        link: 'https://amzn.to/3RA6R6H',
        publishDate: '2026-05-22'
    },
    {
        id: 'CX-26-007',
        name: 'Godrej aer O Hanging Car Air Freshener Pack',
        category: 'car-accessories',
        catLabel: 'Car Accessories',
        badge: 'hot',
        price: 245,
        pLabel: 'Now At',
        pDisplay: '₹245',
        pOld: '₹297',
        discount: 18,
        desc: 'A stylish hanging gel-based car air freshener pack with long-lasting fragrance for up to 30 days. Designed to keep your car fresh, odor-free, and pleasant during every drive.',
        tags: ['Air Freshener', 'Long Lasting', 'Car Interior', 'Odor Control', 'Gel Freshener', 'Godrej'],
        link: 'https://amzn.to/49iFcgO',
        publishDate: '2026-05-22'
    },
    {
        id: 'CX-26-008',
        name: 'Yuoyar Magnetic Sunglasses Holder for Car',
        category: 'car-accessories',
        catLabel: 'Car Accessories',
        badge: 'deal',
        price: 289,
        pLabel: 'Now At',
        pDisplay: '₹289',
        pOld: '₹999',
        discount: 71,
        desc: 'A premium magnetic leather sunglasses holder designed for car visors. Keeps your sunglasses secure, scratch-free, and easily accessible while driving with convenient single-hand operation.',
        tags: ['Sunglasses Holder', 'Magnetic Clip', 'Car Organizer', 'Leather Finish', 'Visor Accessory', 'Yuoyar'],
        link: 'https://amzn.to/4fzffNF',
        publishDate: '2026-05-22'
    },
    {
        id: 'CX-26-009',
        name: 'Cinati Under Desk Cable Management Tray',
        category: 'desk-setup',
        catLabel: 'Desk Setup',
        badge: 'hot',
        price: 1999,
        pLabel: 'Now At',
        pDisplay: '₹1999',
        pOld: '₹2999',
        discount: 33,
        desc: 'An extra-large no-drill under desk cable management tray designed to organize wires, adapters, and power strips neatly. Features sturdy metal construction, clamp installation, and a clean clutter-free setup for home or office desks.',
        tags: ['Cable Management', 'Desk Setup', 'No Drill', 'Wire Organizer', 'Workspace', 'Cinati'],
        link: 'https://amzn.to/42Z9wtb',
        publishDate: '2026-05-27'
    },
    {
        id: 'CX-26-010',
        name: 'VSDinside 18-Key Stream Controller Macro Pad',
        category: 'desk-setup',
        catLabel: 'Desk Setup',
        badge: 'hot',
        price: 8194.87,
        pLabel: 'Now At',
        pDisplay: '₹8,194',
        pOld: '₹30,314',
        discount: 73,
        desc: 'A premium 18-key programmable macro pad with customizable LCD keys, RGB lighting, and one-touch shortcuts for gaming, streaming, editing, and productivity workflows. Perfect for creators, streamers, and advanced desk setups.',
        tags: ['Macro Keyboard', 'Stream Deck', 'RGB', 'Gaming Setup', 'Productivity', 'VSDinside'],
        link: 'https://amzn.to/4vivJi9',
        publishDate: '2026-05-27'
    },
    {
        id: 'CX-26-011',
        name: 'Portronics Tornado High-Speed Air Duster',
        category: 'desk-setup',
        catLabel: 'Desk Setup',
        badge: 'hot',
        price: 2399,
        pLabel: 'Now At',
        pDisplay: '₹2,399',
        pOld: '₹4,999',
        discount: 52,
        desc: 'A powerful cordless handheld air duster with up to 130000 RPM airflow, adjustable speed modes, and Type-C charging. Perfect for cleaning keyboards, PCs, cameras, car interiors, and hard-to-reach electronics.',
        tags: ['Air Duster', 'Desk Setup', 'Cleaning Tool', 'Rechargeable', 'High Speed', 'Portronics'],
        link: 'https://amzn.to/4dyVTqJ',
        publishDate: '2026-05-27'
    },
    {
        id: 'CX-26-012',
        name: 'PxIn Privacy Screen Filter for Laptop',
        category: 'desk-setup',
        catLabel: 'Desk Setup',
        badge: 'hot',
        price: 1598,
        pLabel: 'Now At',
        pDisplay: '₹1,598',
        pOld: '₹2,999',
        discount: 47,
        desc: 'A premium anti-glare privacy screen filter with blue light protection designed to reduce eye strain and protect sensitive information in public spaces. Ideal for laptops and work-from-anywhere setups.',
        tags: ['Privacy Screen', 'Anti Glare', 'Blue Light Filter', 'Laptop Accessory', 'Eye Protection', 'PxIn'],
        link: 'https://amzn.to/4nPp9gm',
        publishDate: '2026-05-27'
    },
    {
        id: 'CX-26-013',
        name: 'Portronics Mport 8 USB-C Hub',
        category: 'desk-setup',
        catLabel: 'Desk Setup',
        badge: 'deal',
        price: 1073,
        pLabel: 'Now At',
        pDisplay: '₹1,073',
        pOld: '₹2,999',
        discount: 64,
        desc: 'An 8-in-1 USB-C docking hub with 4K HDMI output, Ethernet, USB 3.0, SD/microSD card readers, and PD charging support. A compact productivity essential for laptops, MacBooks, and modern desk setups.',
        tags: ['USB-C Hub', 'Docking Station', '4K HDMI', 'Desk Setup', 'Productivity', 'Portronics'],
        link: 'https://amzn.to/4dOFopx',
        publishDate: '2026-05-27'
    },
    {
        id: 'CX-26-014',
        name: 'Mengshen Door Stop Alarm',
        category: 'home-security',
        catLabel: 'Home Security',
        badge: 'hot',
        price: 979,
        pLabel: 'Now At',
        pDisplay: '₹979',
        pOld: '₹1,049',
        discount: 7,
        desc: 'A portable door stop alarm that combines physical door blocking with a powerful 120dB security alert. Ideal for homes, apartments, dorms, hotels, and solo travelers seeking extra peace of mind.',
        tags: ['Door Alarm', 'Home Security', 'Travel Essential', '120dB Alert', 'Portable Safety', 'Mengshen'],
        link: 'https://amzn.to/4ehbOcz',
        publishDate: '2026-05-30'
    },
    {
        id: 'CX-26-015',
        name: 'SaleOn Tech Organizer Pouch',
        category: 'travel-accessories',
        catLabel: 'Travel Accessories',
        badge: 'deal',
        price: 294,
        pLabel: 'Now At',
        pDisplay: '₹294',
        pOld: '₹889',
        discount: 67,
        desc: 'A compact waterproof tech organizer pouch with dual-layer compartments, mesh pockets, and elastic loops to neatly store cables, chargers, power banks, hard drives, and everyday gadgets while traveling.',
        tags: ['Tech Pouch', 'Cable Organizer', 'Travel Essential', 'Waterproof', 'Gadget Storage', 'SaleOn'],
        link: 'https://amzn.to/4nYuNwB',
        publishDate: '2026-05-30'
    },
    {
        id: 'CX-26-016',
        name: 'Portable Retractable Travel Clothesline',
        category: 'travel-accessories',
        catLabel: 'Travel Accessories',
        badge: 'deal',
        price: 199,
        pLabel: 'Now At',
        pDisplay: '₹199',
        pOld: '₹399',
        discount: 50,
        desc: 'A lightweight retractable clothesline with 12 clips and anti-slip positioning beads, perfect for drying clothes while traveling, camping, staying in hotels, or using at home. Compact, portable, and easy to set up anywhere.',
        tags: ['Travel Essential', 'Portable Clothesline', 'Camping Gear', 'Laundry Organizer', 'Outdoor Travel', 'HONGYUTAI'],
        link: 'https://amzn.to/4uJ9diu',
        publishDate: '2026-05-30'
    },
    {
        id: 'CX-26-017',
        name: 'MattEasy Vacuum Storage Bags with Electric Pump',
        category: 'travel-accessories',
        catLabel: 'Travel Accessories',
        badge: 'hot',
        price: 749,
        pLabel: 'Now At',
        pDisplay: '₹749',
        pOld: '₹1,299',
        discount: 42,
        desc: 'A 6-pack vacuum storage bag set with an included electric pump that compresses clothes, blankets, bedding, and travel essentials to save up to 80% of storage space. Ideal for travel, moving, and seasonal organization.',
        tags: ['Vacuum Bags', 'Space Saver', 'Travel Organizer', 'Electric Pump', 'Storage Solution', 'MattEasy'],
        link: 'https://amzn.to/4dOMZnN',
        publishDate: '2026-05-30'
    },
    {
        id: 'CX-26-018',
        name: 'LifeStraw Personal Water Filter',
        category: 'travel-accessories',
        catLabel: 'Travel Accessories',
        badge: 'hot',
        price: 1290,
        pLabel: 'Now At',
        pDisplay: '₹1,290',
        pOld: '₹1,590',
        discount: 19,
        desc: 'An ultra-portable personal water filter that removes 99.99% of waterborne bacteria and provides up to 1,000 liters of safe drinking water. Essential for hiking, camping, international travel, emergency kits, and outdoor adventures.',
        tags: ['Water Filter', 'Survival Gear', 'Travel Essential', 'Camping', 'Emergency Preparedness', 'LifeStraw'],
        link: 'https://amzn.to/4viJAou',
        publishDate: '2026-05-30'
    },
    {
        id: 'CX-26-019',
        name: 'Poligono Inverted Windproof Umbrella',
        category: 'travel-accessories',
        catLabel: 'Travel Accessories',
        badge: 'hot',
        price: 699,
        pLabel: 'Now At',
        pDisplay: '₹699',
        pOld: '₹1,299',
        discount: 46,
        desc: 'A premium inverted folding umbrella with automatic open-close functionality, reflective safety strips, and a sturdy 10-rib windproof frame. Designed to keep you dry while preventing water from dripping onto your car or indoor spaces.',
        tags: ['Umbrella', 'Monsoon Essential', 'Windproof', 'Auto Open', 'Travel Accessory', 'Poligono'],
        link: 'https://amzn.to/4380ytL',
        publishDate: '2026-05-31'
    },
    {
        id: 'CX-26-020',
        name: 'ANYCHO Waterproof Silicone Shoe Covers',
        category: 'travel-accessories',
        catLabel: 'Travel Accessories',
        badge: 'hot',
        price: 599,
        pLabel: 'Now At',
        pDisplay: '₹599',
        pOld: '₹999',
        discount: 40,
        desc: 'Reusable waterproof silicone shoe covers designed to keep your shoes dry during rain, puddles, mud, and outdoor adventures. Features a double-layer waterproof design, anti-slip sole, and compact foldable storage for everyday carry.',
        tags: ['Monsoon Essential', 'Shoe Covers', 'Waterproof', 'Travel Accessory', 'Reusable', 'ANYCHO'],
        link: 'https://amzn.to/4nYzqqF',
        publishDate: '2026-05-31'
    },
    {
        id: 'CX-26-021',
        name: 'ROCKSPORT Waterproof Rain Poncho',
        category: 'travel-accessories',
        catLabel: 'Travel Accessories',
        badge: 'hot',
        price: 745,
        pLabel: 'Now At',
        pDisplay: '₹745',
        pOld: '₹1,199',
        discount: 38,
        desc: 'A lightweight waterproof rain poncho with full-sleeve coverage, adjustable hood, and backpack-friendly design. Compact, reusable, and ideal for monsoon commutes, travel, trekking, camping, and outdoor adventures.',
        tags: ['Rain Poncho', 'Monsoon Essential', 'Waterproof', 'Travel Gear', 'Camping', 'ROCKSPORT'],
        link: 'https://amzn.to/3Rw1Xb5',
        publishDate: '2026-05-31'
    },
    {
        id: 'CX-26-022',
        name: 'SOFTSPUN Premium Microfiber Cleaning Cloths',
        category: 'car-accessories',
        catLabel: 'Car Accessories',
        badge: 'deal',
        price: 259,
        pLabel: 'Now At',
        pDisplay: '₹259',
        pOld: '₹604',
        discount: 57,
        desc: 'A pack of premium 340 GSM microfiber cloths designed for streak-free cleaning, drying, polishing, and detailing. Ultra-soft, highly absorbent, and scratch-free for cars, bikes, electronics, and household surfaces.',
        tags: ['Microfiber Cloth', 'Car Detailing', 'Scratch Free', 'Cleaning Essential', 'High Absorbency', 'SOFTSPUN'],
        link: 'https://amzn.to/4nW4GGC',
        publishDate: '2026-05-31'
    },
    {
        id: 'CX-26-023',
        name: 'Boldfit Waterproof Backpack Rain Cover',
        category: 'travel-accessories',
        catLabel: 'Travel Accessories',
        badge: 'deal',
        price: 151,
        pLabel: 'Now At',
        pDisplay: '₹151',
        pOld: '₹399',
        discount: 62,
        desc: 'A lightweight waterproof backpack rain cover with adjustable buckle and elastic hem for a secure fit. Protects bags up to 45L from rain, dust, and moisture during travel, trekking, cycling, and outdoor adventures.',
        tags: ['Rain Cover', 'Backpack Protector', 'Waterproof', 'Travel Essential', 'Outdoor Gear', 'Boldfit'],
        link: 'https://amzn.to/3PLC6LJ',
        publishDate: '2026-05-31'
    },
    {
        id: 'CX-26-024',
        name: 'One94Store Motion Sensor Under Cabinet LED Light',
        category: 'home-essentials',
        catLabel: 'Home Essentials',
        badge: 'deal',
        price: 308,
        pLabel: 'Now At',
        pDisplay: '₹308',
        pOld: '₹999',
        discount: 69,
        desc: 'A rechargeable motion-sensor LED cabinet light with 3 dimmable brightness modes. Perfect for wardrobes, kitchens, staircases, and closets with easy stick-on installation and wireless operation.',
        tags: ['Motion Sensor', 'LED Light', 'Wardrobe Light', 'USB Rechargeable', 'Cabinet Lighting', 'One94Store'],
        link: 'https://amzn.to/4dXp2e3',
        publishDate: '2026-06-03'
    },
    {
        id: 'CX-26-025',
        name: 'Gecko Natural Shoe & Sneaker Deodorizer Spray',
        category: 'personal-care',
        catLabel: 'Personal Care',
        badge: 'deal',
        price: 301,
        pLabel: 'Now At',
        pDisplay: '₹301',
        pOld: '₹525',
        discount: 43,
        desc: 'A powerful shoe deodorizer spray that eliminates stubborn odours and keeps footwear fresh with a natural peppermint and eucalyptus fragrance. Suitable for sneakers, sports shoes, work boots, and everyday footwear.',
        tags: ['Shoe Freshener', 'Odour Eliminator', 'Sneaker Care', 'Foot Care', 'Peppermint Formula', 'Gecko'],
        link: 'https://amzn.to/4dWpBoA',
        publishDate: '2026-06-03'
    },
    {
        id: 'CX-26-026',
        name: 'One94Store Rechargeable Panda Night Light',
        category: 'home-essentials',
        catLabel: 'Home Essentials',
        badge: 'deal',
        price: 359,
        pLabel: 'Now At',
        pDisplay: '₹359',
        pOld: '₹999',
        discount: 64,
        desc: 'An adorable BPA-free silicone panda night light with 7 color-changing LED modes, rechargeable battery, and soft squeeze-friendly design. Perfect for kids’ bedrooms, nurseries, bedtime comfort, and cute room décor.',
        tags: ['Night Light', 'Panda Lamp', 'Kids Room', 'Rechargeable', '7 Colors', 'Silicone Lamp'],
        link: 'https://amzn.to/4e6ARyJ',
        publishDate: '2026-06-03'
    },
    {
        id: 'CX-26-027',
        name: 'RTS Universal Travel Adapter with Dual USB',
        category: 'travel-accessories',
        catLabel: 'Travel Accessories',
        badge: 'deal',
        price: 499,
        pLabel: 'Now At',
        pDisplay: '₹499',
        pOld: '₹4999',
        discount: 90,
        desc: 'An all-in-one universal travel adapter compatible with over 150 countries, featuring US/EU/UK/AU plug support, dual USB charging ports, and built-in safety protection. Perfect for international travel, business trips, and charging multiple devices worldwide.',
        tags: ['Travel Adapter', 'Universal Plug', 'Dual USB', 'Worldwide Travel', 'International Charger', 'RTS'],
        link: 'https://amzn.to/4em4Wvr',
        publishDate: '2026-06-03'
    },
    {
        id: 'CX-26-028',
        name: 'FLYNGO Rechargeable LED Study Lamp with Organizer',
        category: 'desk-setup',
        catLabel: 'Desk Setup',
        badge: 'deal',
        price: 375,
        pLabel: 'Now At',
        pDisplay: '₹375',
        pOld: '₹999',
        discount: 62,
        desc: 'A rechargeable LED study lamp featuring 3 color modes, adjustable brightness, flexible gooseneck design, and built-in pen and phone holders for an organized workspace.',
        tags: ['Study Lamp', 'Desk Organizer', 'LED Light', 'Rechargeable', 'Phone Holder', 'Student Essential'],
        link: 'https://amzn.to/4em4OMt',
        publishDate: '2026-06-03'
    },
    {
        id: 'CX-26-029',
        name: 'SYVO WT3130 Lightweight Aluminum Tripod',
        category: 'mobile-accessories',
        catLabel: 'Mobile Accessories',
        badge: 'deal',
        price: 799,
        pLabel: 'Now At',
        pDisplay: '₹799',
        pOld: '₹3999',
        discount: 80,
        desc: 'A lightweight 50-inch aluminum tripod with smartphone holder, bubble level, 360° pan head, and carry bag. Perfect for mobile photography, videography, vlogging, time-lapse shots, and content creation.',
        tags: ['Tripod', 'Mobile Photography', 'Camera Stand', 'Content Creator', 'Vlogging Gear', 'SYVO'],
        link: 'https://amzn.to/4ucGIsd',
        publishDate: '2026-06-06'
    },
    {
        id: 'CX-26-030',
        name: 'Portronics UFO 6-Port USB Charging Station',
        category: 'mobile-accessories',
        catLabel: 'Mobile Accessories',
        badge: 'deal',
        price: 624,
        pLabel: 'Now At',
        pDisplay: '₹624',
        pOld: '₹1299',
        discount: 52,
        desc: 'A compact 6-port USB charging station with 8A total output and smart IC technology, allowing multiple smartphones, tablets, and gadgets to charge simultaneously with built-in safety protection.',
        tags: ['USB Charger', 'Charging Station', 'Fast Charging', '6 Port Hub', 'Desk Setup', 'Portronics'],
        link: 'https://amzn.to/4fp3xFw',
        publishDate: '2026-06-06'
    },
    {
        id: 'CX-26-031',
        name: 'MAXXOX 2-in-1 Mobile Camera Lens Kit',
        category: 'mobile-accessories',
        catLabel: 'Mobile Accessories',
        badge: 'deal',
        price: 299,
        pLabel: 'Now At',
        pDisplay: '₹299',
        pOld: '₹1299',
        discount: 77,
        desc: 'A clip-on mobile camera lens kit featuring a 0.45X wide-angle lens and 15X macro lens, perfect for smartphone photography, vlogging, reels, product shots, and close-up detail capture.',
        tags: ['Mobile Lens', 'Wide Angle Lens', 'Macro Lens', 'Content Creator', 'Mobile Photography', 'Vlogging'],
        link: 'https://amzn.to/4esp92E',
        publishDate: '2026-06-06'
    },
    {
        id: 'CX-26-032',
        name: 'Lapster Luma Core Rechargeable LED Video Light',
        category: 'mobile-accessories',
        catLabel: 'Mobile Accessories',
        badge: 'deal',
        price: 599,
        pLabel: 'Now At',
        pDisplay: '₹599',
        pOld: '₹999',
        discount: 40,
        desc: 'A compact rechargeable LED video light with adjustable brightness, 3 color modes, and a clip-on design. Perfect for content creators, video calls, vlogging, photography, YouTube videos, and live streaming.',
        tags: ['Video Light', 'Content Creator', 'Vlogging', 'Photography', 'YouTube Setup', 'LED Light'],
        link: 'https://amzn.to/4g47Juz',
        publishDate: '2026-06-06'
    },
    {
        id: 'CX-26-033',
        name: 'ZEITEL Mini Bluetooth Thermal Label Printer',
        category: 'desk-setup',
        catLabel: 'Desk Setup',
        badge: 'deal',
        price: 1330,
        pLabel: 'Now At',
        pDisplay: '₹1330',
        pOld: '₹3695',
        discount: 64,
        desc: 'A portable Bluetooth thermal printer that prints labels, stickers, notes, lists, and photos without ink. Includes 13 paper rolls and app-based printing support for Android and iOS devices.',
        tags: ['Thermal Printer', 'Label Maker', 'Bluetooth Printer', 'Desk Setup', 'Study Essential', 'Portable Printer'],
        link: 'https://amzn.to/3QlC8tU',
        publishDate: '2026-06-06'
    },
    {
        id: 'CX-26-034',
        name: 'Story@Home 100% Blackout Door Curtain',
        category: 'home-finds',
        catLabel: 'Home Finds',
        badge: 'deal',
        price: 699,
        pLabel: 'Now At',
        pDisplay: '₹699',
        pOld: '₹1699',
        discount: 59,
        desc: 'Premium 7-foot blackout curtain with 100% light blocking, thermal insulation, noise reduction, and complete privacy. Ideal for bedrooms, living rooms, offices, and home theaters while helping maintain room temperature throughout the year.',
        tags: ['Blackout Curtain', 'Home Decor', 'Room Darkening', 'Thermal Insulated', 'Privacy Curtain', 'Bedroom Essential'],
        link: 'https://amzn.to/4fr7MAo',
        publishDate: '2026-06-07'
    },
    {
        id: 'CX-26-035',
        name: 'Amazon Basics Suction Towel Holder',
        category: 'home-finds',
        catLabel: 'Home Finds',
        badge: 'deal',
        price: 1599,
        pLabel: 'Now At',
        pDisplay: '₹1599',
        pOld: '₹2999',
        discount: 47,
        desc: 'A premium drill-free towel rack with powerful vacuum suction mounting and rustproof aluminum construction. Features a towel bar with multiple hooks, making it perfect for organizing towels, robes, and bathroom essentials without damaging walls.',
        tags: ['Bathroom Organizer', 'Towel Rack', 'No Drill', 'Home Improvement', 'Rustproof', 'Space Saver'],
        link: 'https://amzn.to/4fwt0Nq',
        publishDate: '2026-06-07'
    },
    {
        id: 'CX-26-036',
        name: 'Hallstatt Extendable Microfiber Ceiling Duster',
        category: 'home-finds',
        catLabel: 'Home Finds',
        badge: 'deal',
        price: 299,
        pLabel: 'Now At',
        pDisplay: '₹299',
        pOld: '₹999',
        discount: 70,
        desc: 'An extendable microfiber duster with a 100-inch stainless steel telescopic pole and bendable head for effortlessly cleaning ceiling fans, cobwebs, walls, blinds, and hard-to-reach corners. Features a washable, reusable, anti-scratch design with a protective rubber tip.',
        tags: ['Cleaning Tool', 'Ceiling Duster', 'Microfiber Duster', 'Home Essential', 'Extendable Pole', 'Reusable'],
        link: 'https://amzn.to/3Q9sHO1',
        publishDate: '2026-06-07'
    },
    {
        id: 'CX-26-037',
        name: 'Kuber Industries Multipurpose Storage Basket Set (Pack of 3)',
        category: 'home-finds',
        catLabel: 'Home Finds',
        badge: 'deal',
        price: 419,
        pLabel: 'Now At',
        pDisplay: '₹419',
        pOld: '₹939',
        discount: 55,
        desc: 'A pack of 3 sturdy plastic storage baskets with lids and side-grip handles for organizing toiletries, cosmetics, pantry items, toys, office supplies, and everyday essentials. Waterproof, lightweight, and stackable for clutter-free storage.',
        tags: ['Storage Basket', 'Home Organization', 'Bathroom Storage', 'Kitchen Organizer', 'Closet Organizer', 'Storage Box', 'Home Essential', 'Pack of 3'],
        link: 'https://amzn.to/4xdjnJD',
        publishDate: '2026-06-07'
    },
    {
        id: 'CX-26-038',
        name: 'AERYS Digital Alarm Clock with Temperature Display',
        category: 'desk-setup',
        catLabel: 'Desk Setup',
        badge: 'deal',
        price: 299,
        pLabel: 'Now At',
        pDisplay: '₹299',
        pOld: '₹999',
        discount: 70,
        desc: 'A compact digital alarm clock featuring time, date, and temperature display with an automatic night-light sensor. Includes a loud crescendo alarm, easy-to-read LCD screen, and battery-powered design, making it ideal for desks, bedrooms, study tables, and office spaces.',
        tags: ['Digital Clock', 'Alarm Clock', 'Desk Setup', 'Study Essential', 'Temperature Display', 'LCD Display', 'Bedroom Decor', 'Office Accessory'],
        link: 'https://amzn.to/4ogUEAf',
        publishDate: '2026-06-07'
    },
    {
        id: 'CX-26-039',
        name: 'Pisol 6-in-1 Kitchen Gadget Set',
        category: 'kitchen-finds',
        catLabel: 'Kitchen Finds',
        badge: 'deal',
        price: 378,
        pLabel: 'Now At',
        pDisplay: '₹378',
        pOld: '₹999',
        discount: 62,
        desc: 'A compact 6-in-1 kitchen tool set featuring a cheese grater, bottle opener, fruit and vegetable peeler, pizza cutter, ginger grinder, and herb stripper. Space-saving stackable design with stainless steel blades for everyday kitchen tasks.',
        tags: ['Kitchen Gadget', '6-in-1 Tool', 'Vegetable Peeler', 'Cheese Grater', 'Pizza Cutter', 'Kitchen Organizer', 'Cooking Essential', 'Space Saving'],
        link: 'https://amzn.to/4uplVSy',
        publishDate: '2026-06-07'
    },
    {
        id: 'CX-26-040',
        name: 'OrganizeMee Magnetic Fridge Spice Rack',
        category: 'kitchen-finds',
        catLabel: 'Kitchen Finds',
        badge: 'deal',
        price: 688,
        pLabel: 'Now At',
        pDisplay: '₹688',
        pOld: '₹1299',
        discount: 47,
        desc: 'A sturdy magnetic storage rack that instantly adds extra storage space on refrigerators, washing machines, microwaves, and other metal surfaces. Perfect for organizing spices, bottles, seasonings, coffee jars, and everyday kitchen essentials without drilling.',
        tags: ['Spice Rack', 'Magnetic Shelf', 'Kitchen Organizer', 'Fridge Storage', 'Space Saver', 'No Drill Installation', 'Home Organization', 'Kitchen Essential'],
        link: 'https://amzn.to/4e94jUK',
        publishDate: '2026-06-07'
    },
    {
        id: 'CX-26-041',
        name: 'Primesky Rechargeable Mini Milk Frother',
        category: 'kitchen-finds',
        catLabel: 'Kitchen Finds',
        badge: 'deal',
        price: 199,
        pLabel: 'Now At',
        pDisplay: '₹199',
        pOld: '₹499',
        discount: 60,
        desc: 'A rechargeable handheld milk frother with 3 adjustable speed modes for creating café-style coffee, cappuccinos, lattes, matcha, hot chocolate, and whipped drinks at home. Features a stainless steel whisk, USB charging, and compact portable design.',
        tags: ['Milk Frother', 'Coffee Maker', 'Kitchen Gadget', 'Rechargeable', 'Coffee Lover', 'Matcha Mixer', 'Handheld Blender', 'Kitchen Essential'],
        link: 'https://amzn.to/3PLl0O7',
        publishDate: '2026-06-07'
    },
    {
        id: 'CX-26-042',
        name: 'SATVIKAYA Airtight Kitchen Storage Container Set',
        category: 'kitchen-finds',
        catLabel: 'Kitchen Finds',
        badge: 'deal',
        price: 389,
        pLabel: 'Now At',
        pDisplay: '₹389',
        pOld: '₹1999',
        discount: 81,
        desc: 'A set of airtight BPA-free storage containers designed to keep grains, cereals, pulses, dry fruits, and pantry essentials fresh for longer. Leak-proof, stackable, and space-saving design helps organize kitchen shelves, pantries, and refrigerators efficiently.',
        tags: ['Storage Container', 'Airtight Container', 'Kitchen Organizer', 'Pantry Storage', 'Fridge Organizer', 'Food Storage', 'Space Saving', 'Kitchen Essential'],
        link: 'https://amzn.to/4uhh45B',
        publishDate: '2026-06-07'
    },
    {
        id: 'CX-26-043',
        name: 'Umite Chef 2-Tier Under Sink Organizer Rack',
        category: 'home-organization',
        catLabel: 'Home Organization',
        badge: 'deal',
        price: 499,
        pLabel: 'Now At',
        pDisplay: '₹499',
        pOld: '₹1899',
        discount: 74,
        desc: 'A space-saving 2-tier under-sink organizer with slide-out baskets, removable dividers, hooks, and drainage design. Perfect for organizing kitchen, bathroom, laundry, and pantry essentials while maximizing cabinet space.',
        tags: ['Under Sink Organizer', 'Kitchen Storage', 'Bathroom Organizer', 'Home Organization', 'Cabinet Rack', 'Space Saver'],
        link: 'https://amzn.to/4ulfAri',
        publishDate: '2026-06-07'
    },
    {
        id: 'CX-26-044',
        name: 'BRONTIX Period Cramp Relief Heating Massager',
        category: 'finds-for-women',
        catLabel: 'Finds for Women',
        badge: 'deal',
        price: 1398,
        pLabel: 'Now At',
        pDisplay: '₹1398',
        pOld: '₹4000',
        discount: 65,
        desc: 'A cordless menstrual pain relief belt with 6 heat and 6 vibration modes that helps soothe period cramps, lower back pain, and abdominal discomfort anytime, anywhere.',
        tags: ['Period Relief', 'Heating Pad', 'Women Finds', 'Pain Relief', 'Rechargeable', 'Wellness Gadget'],
        link: 'https://amzn.to/4e199Vl',
        publishDate: '2026-06-11'
    },
    {
        id: 'CX-26-045',
        name: 'Mini Jewellery Travel Organizer Case',
        category: 'travel-finds-for-women',
        catLabel: 'Travel Finds for Women',
        badge: 'deal',
        price: 281,
        pLabel: 'Now At',
        pDisplay: '₹281',
        pOld: '₹318',
        discount: 12,
        desc: 'A compact faux leather jewellery organizer with velvet-lined compartments, necklace hooks, ring slots, and earring storage to keep accessories protected and tangle-free while travelling.',
        tags: ['Jewellery Organizer', 'Travel Essential', 'Women Finds', 'Storage Box', 'Travel Accessories', 'Gift Idea'],
        link: 'https://amzn.to/4eAfp6z',
        publishDate: '2026-06-11'
    },
    {
        id: 'CX-26-046',
        name: 'Lyrovo Leak-Proof Travel Bottles Kit',
        category: 'travel-finds-for-women',
        catLabel: 'Travel Finds for Women',
        badge: 'deal',
        price: 330,
        pLabel: 'Now At',
        pDisplay: '₹330',
        pOld: '₹999',
        discount: 67,
        desc: 'A set of four TSA-approved silicone travel bottles with leak-proof design, wide-mouth filling, and reusable BPA-free construction for carrying toiletries, lotions, and skincare essentials.',
        tags: ['Travel Bottles', 'Travel Essential', 'Women Finds', 'Toiletry Organizer', 'Leak Proof', 'Travel Accessories'],
        link: 'https://amzn.to/4xcfHYG',
        publishDate: '2026-06-11'
    },
    {
        id: 'CX-26-047',
        name: 'Vega 3-in-1 Hair Styler',
        category: 'finds-for-women',
        catLabel: 'Finds for Women',
        badge: 'deal',
        price: 1539,
        pLabel: 'Now At',
        pDisplay: '₹1539',
        pOld: '₹1999',
        discount: 23,
        desc: 'A versatile 3-in-1 hair styling tool that works as a straightener, curler, and crimper. Features ceramic-coated plates, quick heat-up, a curling clamp, swivel cord, and travel-friendly design for effortless styling.',
        tags: ['Hair Styler', 'Hair Straightener', 'Hair Curler', 'Hair Crimper', 'Beauty Tool', 'Women Finds'],
        link: 'https://amzn.to/3RWIwIE',
        publishDate: '2026-06-11'
    },
    {
        id: 'CX-26-048',
        name: 'Bombae 6-in-1 Sensitive Women Trimmer',
        category: 'finds-for-women',
        catLabel: 'Finds for Women',
        badge: 'deal',
        price: 1399,
        pLabel: 'Now At',
        pDisplay: '₹1399',
        pOld: '₹1599',
        discount: 13,
        desc: 'A versatile 6-in-1 women’s grooming trimmer designed for facial hair, eyebrows, bikini area, underarms, and body grooming. Features skin-friendly blades, waterproof design, USB Type-C charging, and up to 90 minutes of cordless runtime.',
        tags: ['Women Trimmer', 'Bikini Trimmer', 'Facial Hair Remover', 'Body Groomer', 'Rechargeable', 'Women Finds'],
        link: 'https://amzn.to/4xmstnE',
        publishDate: '2026-06-11'
    },
    {
        id: 'CX-26-049',
        name: 'Hetkrishi 11-in-1 Wallet Ninja Multi Tool',
        category: 'finds-for-men',
        catLabel: 'Finds for Men',
        badge: 'deal',
        price: 159,
        pLabel: 'Now At',
        pDisplay: '₹159',
        pOld: '₹399',
        discount: 60,
        desc: 'A credit card-sized 11-in-1 stainless steel multi-tool featuring a bottle opener, screwdriver, ruler, wrench, saw blade, can opener, and more. Compact enough to fit in your wallet, pocket, backpack, or glove box for everyday emergencies.',
        tags: ['Multi Tool', 'Wallet Tool', 'Pocket Tool', 'EDC Gear', 'Camping Tool', 'Men Finds'],
        link: 'https://amzn.to/4va38vG',
        publishDate: '2026-06-12'
    },
    {
        id: 'CX-26-050',
        name: 'Coquimbo COB Rechargeable LED Work Light (2 Pack)',
        category: 'finds-for-men',
        catLabel: 'Finds for Men',
        badge: 'deal',
        price: 569,
        pLabel: 'Now At',
        pDisplay: '₹569',
        pOld: '₹1699',
        discount: 67,
        desc: 'A rechargeable COB LED work light set with 5 lighting modes, 360° rotating body, magnetic base, and hanging hook. Perfect for car repairs, camping, power outages, emergency use, and hands-free lighting anywhere.',
        tags: ['LED Work Light', 'Rechargeable Torch', 'Magnetic Light', 'Camping Gear', 'Emergency Light', 'Men Finds'],
        link: 'https://amzn.to/4v29SLW',
        publishDate: '2026-06-12'
    },
    {
        id: 'CX-26-051',
        name: 'SNEAKARE Quick Shoe Cleaning Kit',
        category: 'finds-for-men',
        catLabel: 'Finds for Men',
        badge: 'deal',
        price: 298,
        pLabel: 'Now At',
        pDisplay: '₹298',
        pOld: '₹449',
        discount: 33,
        desc: 'A quick-clean shoe care kit featuring a premium foam cleaner and medium-bristle brush. Safe for sneakers, sports shoes, canvas, leather, mesh, and knit materials, helping restore shoes with minimal effort.',
        tags: ['Shoe Cleaner', 'Sneaker Care', 'Cleaning Kit', 'Shoe Brush', 'Sneaker Essential', 'Men Finds'],
        link: 'https://amzn.to/4aFgEPt',
        publishDate: '2026-06-12'
    },
    {
        id: 'CX-26-052',
        name: 'THEMISTO 27-in-1 Precision Screwdriver Set',
        category: 'finds-for-men',
        catLabel: 'Finds for Men',
        badge: 'deal',
        price: 249,
        pLabel: 'Now At',
        pDisplay: '₹249',
        pOld: '₹652',
        discount: 62,
        desc: 'A compact 27-in-1 precision repair toolkit featuring 25 interchangeable screwdriver bits, 2 mobile opening tools, and an aviation-grade aluminum handle. Ideal for repairing smartphones, laptops, watches, glasses, cameras, and other electronics.',
        tags: ['Precision Screwdriver', 'Repair Kit', 'Electronics Tool', 'Mobile Repair', 'DIY Tool', 'Men Finds'],
        link: 'https://amzn.to/3QDPKRp',
        publishDate: '2026-06-12'
    },
    {
        id: 'CX-26-053',
        name: 'Philips MG3927 All-in-One Grooming Kit',
        category: 'finds-for-men',
        catLabel: 'Finds for Men',
        badge: 'deal',
        price: 1499,
        pLabel: 'Now At',
        pDisplay: '₹1499',
        pOld: '₹2045',
        discount: 27,
        desc: 'A versatile 9-in-1 grooming kit for beard, hair, body, nose, and ear trimming. Features self-sharpening steel blades, precision trimming combs, skin-friendly rounded tips, and up to 60 minutes of cordless runtime.',
        tags: ['Trimmer', 'Beard Trimmer', 'Grooming Kit', 'Body Groomer', 'Philips', 'Men Finds'],
        link: 'https://amzn.to/3QDLhy3',
        publishDate: '2026-06-12'
    },
    {
        id: 'CX-26-054',
        name: '101 Reasons Why I Love You Jar with LED Fairy Lights',
        category: 'couples-finds',
        catLabel: 'Finds For Couples',
        badge: 'hot',
        price: 498,
        pLabel: 'Now At',
        pDisplay: '₹498',
        pOld: '₹999',
        discount: 50,
        desc: 'A romantic handmade glass jar featuring 101 heartfelt love notes and warm LED fairy lights. Perfect as an anniversary, birthday, Valentine’s Day, or surprise gift for your partner, creating a memorable keepsake filled with meaningful messages.',
        tags: ['Couple Gift', 'Love Notes Jar', 'Anniversary Gift', 'Valentine Gift', 'Romantic Decor', 'LED Fairy Lights'],
        link: 'https://amzn.to/43tAZDE',
        publishDate: '2026-06-13'
    },
    {
        id: 'CX-26-055',
        name: 'Custom Spotify Photo Fridge Magnet',
        category: 'couples-finds',
        catLabel: 'Finds For Couples',
        badge: 'hot',
        price: 169,
        pLabel: 'Now At',
        pDisplay: '₹169',
        pOld: '₹249',
        discount: 32,
        desc: 'A personalized Spotify-inspired acrylic fridge magnet featuring your favorite photo and custom music code. A meaningful keepsake that combines memories and music, perfect for anniversaries, birthdays, Valentine’s Day, and special moments with loved ones.',
        tags: ['Spotify Gift', 'Photo Fridge Magnet', 'Couple Gift', 'Personalized Gift', 'Anniversary Gift', 'Music Plaque'],
        link: 'https://amzn.to/4varCF7',
        publishDate: '2026-06-13'
    },
    {
        id: 'CX-26-056',
        name: 'Personalized Wedding Couple Caricature Photo Frame',
        category: 'couples-finds',
        catLabel: 'Finds For Couples',
        badge: 'hot',
        price: 483,
        pLabel: 'Now At',
        pDisplay: '₹483',
        pOld: '₹799',
        discount: 40,
        desc: 'A customized tabletop caricature photo frame handcrafted from your photos, turning special memories into a fun and unique keepsake. Perfect for couples, anniversaries, weddings, birthdays, and meaningful gifting occasions.',
        tags: ['Caricature Frame', 'Personalized Gift', 'Couple Gift', 'Wedding Gift', 'Anniversary Gift', 'Photo Frame'],
        link: 'https://amzn.to/447zWtc',
        publishDate: '2026-06-13'
    },
    {
        id: 'CX-26-057',
        name: 'NYRWANA Mr & Mrs Coffee Mug Gift Set',
        category: 'couples-finds',
        catLabel: 'Finds For Couples',
        badge: 'deal',
        price: 789,
        pLabel: 'Now At',
        pDisplay: '₹789',
        pOld: '₹1999',
        discount: 61,
        desc: 'A premium Mr & Mrs ceramic coffee mug set featuring elegant marble design, matching lids, golden spoons, and a luxury gift box. Perfect for couples, weddings, anniversaries, engagements, and romantic gifting occasions.',
        tags: ['Couple Mug Set', 'Mr And Mrs Mug', 'Wedding Gift', 'Anniversary Gift', 'Coffee Mug Set', 'Couple Gift'],
        link: 'https://amzn.to/43wMjik',
        publishDate: '2026-06-13'
    },
    {
        id: 'CX-26-058',
        name: 'Ubrighty Hand Casting Kit for Couples',
        category: 'couples-finds',
        catLabel: 'Finds For Couples',
        badge: 'hot',
        price: 998,
        pLabel: 'Now At',
        pDisplay: '₹998',
        pOld: '₹2899',
        discount: 66,
        desc: 'Create a lasting memory with this DIY hand casting kit that captures every fine detail, fingerprint, and hand impression. Includes molding powder, casting powder, paint, brush, bucket, and accessories, making it a perfect anniversary, wedding, birthday, or couple gift.',
        tags: ['Hand Casting Kit', 'Couple Gift', 'Anniversary Gift', 'Memory Keepsake', 'DIY Craft Kit', 'Romantic Gift'],
        link: 'https://amzn.to/3S7thwv',
        publishDate: '2026-06-13'
    },
    {
        id: 'CX-26-059',
        name: 'Dad Pocket Watch Keychain',
        category: 'fathers-day',
        catLabel: "Father's Day",
        badge: 'deal',
        price: 426,
        pLabel: 'Now At',
        pDisplay: '₹426',
        pOld: '₹699',
        discount: 39,
        desc: 'A vintage-style pocket watch keychain engraved with a heartfelt message for dad. Crafted with a classic antique design and durable metal construction, it serves as a meaningful keepsake for Father’s Day, birthdays, anniversaries, and special occasions.',
        tags: ['Father Gift', 'Dad Keychain', 'Pocket Watch', 'Fathers Day Gift', 'Vintage Keepsake', 'Gift For Dad'],
        link: 'https://amzn.to/4vSIKz4',
        publishDate: '2026-06-16'
    },
    {
        id: 'CX-26-060',
        name: 'Personalised All-in-One Men’s Gift Combo (4 Pcs)',
        category: 'finds-for-men',
        catLabel: 'Finds For Men',
        badge: 'deal',
        price: 949,
        pLabel: 'Now At',
        pDisplay: '₹949',
        pOld: '₹2999',
        discount: 68,
        desc: 'A premium personalized gift combo featuring a custom name wallet, keychain, eyewear case, and passport cover. Crafted in leather-style finish with a sleek black design, making it a thoughtful gift for husbands, fathers, brothers, boyfriends, and special occasions.',
        tags: ['Personalized Gift', 'Men Wallet', 'Passport Cover', 'Keychain', 'Eyewear Case', 'Gift Combo'],
        link: 'https://amzn.to/4emmVkk',
        publishDate: '2026-06-16'
    },
    {
        id: 'CX-26-061',
        name: 'Super Roll Multi-Purpose Tool Roll Up Bag',
        category: 'fathers-day',
        catLabel: 'Father’s Day',
        badge: 'deal',
        price: 389,
        pLabel: 'Now At',
        pDisplay: '₹389',
        pOld: '₹999',
        discount: 61,
        desc: 'A rugged waterproof canvas tool organizer featuring 5 spacious zippered compartments, roll-up storage design, hanging hooks, and secure buckles. Perfect for mechanics, DIY enthusiasts, campers, car owners, and dads who like keeping tools neatly organized and ready to carry anywhere.',
        tags: ['Tool Roll Bag', 'Tool Organizer', 'Canvas Bag', 'Car Emergency Kit', 'DIY Tools', 'Father Gift'],
        link: 'https://amzn.to/4vNvoUB',
        publishDate: '2026-06-16'
    },
    {
        id: 'CX-26-062',
        name: 'pTron Fusion Tunes 10W Mini Karaoke Bluetooth Speaker',
        category: 'fathers-day',
        catLabel: 'Father’s Day',
        badge: 'deal',
        price: 899,
        pLabel: 'Now At',
        pDisplay: '₹899',
        pOld: '₹3199',
        discount: 72,
        desc: 'A compact 10W Bluetooth speaker with a wireless karaoke microphone, RGB party lights, funny voice effects, and up to 8 hours of playtime. Features Bluetooth 5.1, TF card support, Type-C charging, and a portable design for music, karaoke nights, and family gatherings.',
        tags: ['Bluetooth Speaker', 'Karaoke Mic', 'RGB Lights', 'Portable Speaker', 'Party Gadget', 'Music Lover'],
        link: 'https://amzn.to/4gmLzDU',
        publishDate: '2026-06-16'
    },
    {
        id: 'CX-26-063',
        name: 'Park Avenue Good Morning 7-in-1 Grooming Kit',
        category: 'fathers-day',
        catLabel: 'Father’s Day',
        badge: 'deal',
        price: 499,
        pLabel: 'Now At',
        pDisplay: '₹499',
        pOld: '₹799',
        discount: 38,
        desc: 'A complete 7-in-1 grooming hamper featuring deodorant, shaving cream, after shave lotion, premium soap, shaving brush, razor, and a free travel pouch. Designed to deliver a comfortable shaving experience and daily grooming essentials in one premium gift set.',
        tags: ['Grooming Kit', 'Shaving Kit', 'Father Gift', 'Travel Pouch', 'Mens Care', 'Gift Hamper'],
        link: 'https://amzn.to/4uJt3sR',
        publishDate: '2026-06-16'
    },
    {
        id: 'CX-26-064',
        name: 'Fleettrack 4G Lite GPS Vehicle Tracking Device',
        category: 'car-accessories',
        catLabel: 'Car Accessories',
        badge: 'deal',
        price: 999,
        pLabel: 'Now At',
        pDisplay: '₹999',
        pOld: '₹5999',
        discount: 83,
        desc: 'A compact 4G GPS tracker for cars, bikes, scooters, trucks, and buses with real-time location tracking, route history, geo-fence alerts, ignition notifications, driving reports, and anti-theft monitoring. Includes 1-year premium app access and supports Android & iOS devices.',
        tags: ['GPS Tracker', 'Vehicle Security', 'Live Tracking', 'Geo Fence', 'Car Gadget', 'Anti Theft'],
        link: 'https://link.amazon/B0adKVM7m',
        publishDate: '2026-06-21'
    },
    {
        id: 'CX-26-065',
        name: 'Primate Y12 Bluetooth Motorcycle Helmet Headset',
        category: 'automotive-accessories',
        catLabel: 'Automotive Accessories',
        badge: 'deal',
        price: 999,
        pLabel: 'Now At',
        pDisplay: '₹999',
        pOld: '₹2999',
        discount: 67,
        desc: 'Bluetooth 5.3 motorcycle helmet headset with HD calling, HiFi stereo audio, GPS voice navigation support, dual-device connectivity, noise reduction microphone, IP67 waterproof protection, and universal helmet compatibility for Android and iOS riders.',
        tags: ['Motorcycle Headset', 'Bluetooth 5.3', 'Helmet Audio', 'GPS Navigation', 'HD Calling', 'Waterproof', 'Bike Accessories', 'Rider Gear'],
        link: 'https://link.amazon/B01l9or6C',
        publishDate: '2026-06-21'
    },
    {
        id: 'CX-26-066',
        name: 'Turtle Wax Clearvue Rain Repellant 300ml',
        category: 'automotive-accessories',
        catLabel: 'Automotive Accessories',
        badge: 'deal',
        price: 680,
        pLabel: 'Now At',
        pDisplay: '₹680',
        pOld: '₹849',
        discount: 20,
        desc: 'Hydrophobic rain repellent coating for car windshields, windows, mirrors, and helmet visors. Creates an invisible water-beading layer that improves visibility during rain, reduces fogging, enhances wiper performance, and keeps glass cleaner for longer.',
        tags: ['Rain Repellent', 'Hydrophobic Coating', 'Car Care', 'Windshield Treatment', 'Helmet Visor', 'Monsoon Essential', 'Glass Cleaner', 'Turtle Wax'],
        link: 'https://link.amazon/B03d3hAAS',
        publishDate: '2026-06-21'
    },
    {
        id: 'CX-26-067',
        name: 'ViaTerra Trailpack Handlebar Mount Front Bag',
        category: 'cycling-accessories',
        catLabel: 'Cycling Accessories',
        badge: 'deal',
        price: 999,
        pLabel: 'Now At',
        pDisplay: '₹999',
        pOld: '₹999',
        discount: 0,
        desc: 'A rugged 1.2L handlebar-mounted trail bag with universal MOLLE mounting system, padded construction, quick-access mesh pocket, fleece-lined goggle compartment, and dedicated storage for tools, spares, snacks, and trail essentials.',
        tags: ['Cycle Bag', 'Handlebar Bag', 'Trailpack', 'Bike Accessories', 'Cycling Gear', 'MOLLE Mount', 'Adventure Riding', 'Storage Bag'],
        link: 'https://link.amazon/B0cnwNbt1',
        publishDate: '2026-06-21'
    },
    {
        id: 'CX-26-068',
        name: 'OLKINO 12-in-1 Tubeless Tyre Puncture Repair Kit',
        category: 'automotive-accessories',
        catLabel: 'Automotive Accessories',
        badge: 'deal',
        price: 309,
        pLabel: 'Now At',
        pDisplay: '₹309',
        pOld: '₹1250',
        discount: 75,
        desc: 'A complete 12-in-1 tubeless tyre repair kit featuring heavy-duty T-handle tools, 10 high-grip repair plugs, plier, cutter, puncture detection accessories, gloves, valve caps, and a storage bag for quick roadside repairs of cars, bikes, scooters, and SUVs.',
        tags: ['Tyre Repair Kit', 'Puncture Repair', 'Car Accessories', 'Bike Accessories', 'Roadside Emergency', 'Tubeless Tyre', 'Travel Essential', 'Tool Kit'],
        link: 'https://link.amazon/B0gR7XaOa',
        publishDate: '2026-06-21'
    },
    {
        id: 'CX-26-069',
        name: 'ShineXPro Helmet Cleaner & Microfiber Cloth Combo',
        category: 'automotive-accessories',
        catLabel: 'Automotive Accessories',
        badge: 'deal',
        price: 264,
        pLabel: 'Now At',
        pDisplay: '₹264',
        pOld: '₹300',
        discount: 12,
        desc: 'An antibacterial foaming helmet cleaner with microfiber cloth that deep cleans helmet interiors, removes sweat and odors, kills odor-causing bacteria, and leaves a fresh fragrance while remaining safe for skin, hair, and helmet padding.',
        tags: ['Helmet Cleaner', 'Bike Accessories', 'Helmet Care', 'Antibacterial Spray', 'Odor Remover', 'Motorcycle Gear', 'Microfiber Cloth', 'Rider Essential'],
        link: 'https://link.amazon/B03pyjOui',
        publishDate: '2026-06-21'
    }
];